server:
  port: 0

spring:
  application:
    name: ms-hotelgema-gestion-reservas

  profiles:
    default: prod

  config:
    import: "optional:configserver:http://ms-hotelgema-administracion-server-config:7777"
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    # ===============================
    # OPEN FEIGN + CIRCUIT BREAKER
    # ===============================
    openfeign:
      circuitbreaker:
        enabled: true

    # ===============================
    # KAFKA
    # ===============================
    stream:
      defaultBinder: kafka
      bindings:
        producerReservaNotificacion-out-0:
          destination: reserva-notificacion-topic
          contentType: application/json
      kafka:
        binder:
          brokers: kafka:9092

  # ===============================
  # DATABASE
  # ===============================
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ===============================
# RESILIENCE4J
# ===============================
resilience4j:
  circuitbreaker:
    instances:
      ms-hotelgema-gestion-usuarios:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      ms-hotelgema-gestion-habitaciones:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

# ===============================
# EUREKA
# ===============================
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://ms-hotelgema-administracion-server-registry:8761/eureka/
